name: Update station data

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull station data
      run: python data_puller.py
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Updated station data"
        git push
